//
//  User.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.6
//

import Foundation
import UIKit
import AWSDynamoDB

class User: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _age: String?
    var _email: String?
    var _gender: String?
    var _location: String?
    var _profession: String?
    var _university: String?
    var _userName: String?
    
    class func dynamoDBTableName() -> String {

        return "athna-mobilehub-341109729-User"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_age" : "age",
               "_email" : "email",
               "_gender" : "gender",
               "_location" : "location",
               "_profession" : "profession",
               "_university" : "university",
               "_userName" : "userName",
        ]
    }
}
